export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_REVOKE = "AUTH_REVOKE";
export const USER_LOGOUT = "USER_LOGOUT";

export const SET_GIFTLISTS = "SET_GIFTLISTS";
export const SET_GLIST_ACTIVE = "SET_GLIST_ACTIVE";
export const SET_GLIST_INACTIVE = "SET_GLIST_INACTIVE";
export const SET_GLIST_ITEMS = "SET_GLIST_ITEMS";
export const ADD_NEW_GIFT_LIST = "ADD_NEW_GIFT_LIST";
export const MOVE_GLIST_ITEMS = "MOVE_GLIST_ITEMS";
export const EDIT_GIFT_LIST = "EDIT_GIFT_LIST";
export const SHARE_GIFT_LIST = "SHARE_GIFT_LIST";
export const GET_SHARED_LISTS = "GET_SHARED_LISTS";
export const DELETE_GIFT_LISTS = "DELETE_GIFT_LISTS";

export const GET_USER_SHARED_FROM_LISTS = "GET_USER_SHARED_FROM_LISTS";
export const SET_USER_SHARED_LIST_ACTIVE = "SET_USER_SHARED_LIST_ACTIVE";
export const SET_USER_SHARED_LIST_INACTIVE = "SET_USER_SHARED_LIST_INACTIVE";
export const SET_USER_SHARED_LIST_ITEMS = "SET_USER_SHARED_LIST_ITEMS";
export const SET_USER_SHARED_ITEM_ACTIVE = "SET_USER_SHARED_ITEM_ACTIVE";
export const SET_USER_SHARED_ITEM_INACTIVE = "SET_USER_SHARED_ITEM_INACTIVE";

export const SET_CONTACTS = "SET_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACTS = "DELETE_CONTACTS";

export const SET_WISH_LIST = "SET_WISH_LIST";
export const SET_WISH_LIST_ACTIVE = "SET_WISH_LIST_ACTIVE";
export const SET_WISH_LIST_INACTIVE = "SET_WISH_LIST_INACTIVE";
export const MOVE_WISH_LIST_ITEMS = "MOVE_WISH_LIST_ITEMS";
export const ADD_WISH_LIST_ITEM = "ADD_WISH_LIST_ITEM";
export const DELETE_WISH_LIST_ITEMS = "DELETE_WISH_LIST_ITEMS";

export const SEARCH_PUBLIC_LISTS = "SEARCH_PUBLIC_LISTS";
export const SEARCH_PRIVATE_LISTS = "SEARCH_PRIVATE_LISTS";
export const CLEAR_SEARCH_STATE = "CLEAR_SEARCH_STATE";
export const SET_LIST_ACTIVE = "SET_LIST_ACTIVE";
export const SET_LIST_INACTIVE = "SET_LIST_INACTIVE";
export const SET_PUBLIC_LIST_ITEMS = "SET_PUBLIC_LIST_ITEMS";

export const SET_NOTIFICATIONS_COUNT = "SET_NOTIFICATIONS_COUNT";
export const NOTIFICATION_RECIEVED = "NOTIFICATION_RECIEVED";
export const BEGIN_NOTIFICATIONS = "BEGIN_NOTIFICATIONS";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";